### ISSUE TITLE
KPT.exe takes forever to patch 1 ISO

### ISSUE THREAD

**Issue by MediaMaquina** [SpudManTwo/KPT#34]
I wonder why not use something like xdelta? https://www.romhacking.net/utilities/598/
Simple, no dependencies, gets it done in 1/1000 the time KPT.exe does it.
This KPT stays "not responding" for a long long time. Please, consider not using it for releases.
I can't imagine a 1 core weak CPU trying to patch with it.

**Comment by SpudManTwo** [comment]
There may be a misunderstanding because you're looking at an older version of xDelta that actually doesn't support PSP Isos. If you look at the [more updated version listed here.](https://www.romhacking.net/utilities/928/) You can actually see a few of the reasons on why we didn't go this path.

1. It flat won't work on a 32bit system. Because UMD Isos aren't standard Isos, you have to edit the whole thing as a single file. As a byproduct of that, you are dealing with a file greater than 1Gb which throws out the 32 bit compatibility.
2.  It would require us to redistribute the majority of the game's Iso in a xDelta patch format. This is because when working with the Iso, you need to replace the ToC in the binary of the Iso as well as each individual file. When accounting for this, we would need to distribute much of the Iso's binary data, if not the whole Iso as a patch since xDelta wouldn't properly support editing the individual files contained within the Iso. This goes DIRECTLY against our policy of not distributing the Iso. Additionally, it would run us very afoul of the law.
3. It would require us to only support a single version of the Iso. Some people compress their Isos for storage purposes while others leave theirs uncompressed. Because you cannot assume the Iso is going to be same file and because of some weirdness in how PSP UMD Isos are written, it will just outright break the Iso in many cases. I actually tried this and experienced this exact behavior before. Without getting into a super technical answer and the nitty gritty of what is special about a UMD-Iso versus a more standard Iso, just understand that it would restrict people down to only using one exact form (which echoes the same first problem of killing compatibility). 
4. The performance gains aren't actually as drastic as you seem to think. The problem that makes the game run slowly is the amount of files we are diffing and replacing against the original iso. There's actually 600+ files (and more increasing as the translation progresses) getting replaced in the single iso. When I did some experimental tests of using xDelta versus using UMDReplaceK, UMDReplaceK traded blows in performance.

All of this aside regarding xDelta, I am well aware of the performance issues of the current solution. It is something on the roadmap to get fixed eventually, but given that there are other programmatic issues with the game, it's also not something being prioritized at this time. It will be fixed for the full release though.

**Comment by SpudManTwo** [comment]
As of the newest version that I am working on releasing here shortly, this will now be fixed. Please see the current head of the master branch.
