### ISSUE TITLE
How do I dump the strings from DIC?

### ISSUE THREAD

**Issue by Noriverwater** [SpudManTwo/KPT#38]

**Comment by SpudManTwo** [comment]
Unsure as to what you're trying to dump. If you're talking about one of the two DLCs for the game, then support for them doesn't really exist currently. I've managed to dump them manually by hand, but getting the patcher to do so is not a function that exists at this time. It is far down on the road map.

If you're talking about getting other files in the actual iso itself to dump their strings, then the only answer I can give you is that you'd have to decompress the binary files and then scroll through them manually in a hex editor. I've tried extracting them before but because of the nature of these being binary hex files that just so happen to store certain strings (e.g. "Save Game?"), getting these to extract is just a fool's errand. If you'd like, the JP -> EN translation team has a list of excel files where I dumped these manually that I could link you to privately. Contact me via Discord or Email for more information if that is the case.
